// <auto-generated />
using System;
using LDXPS.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LDXPS.Data.Migrations
{
    [DbContext(typeof(ContextoEF))]
    partial class ContextoEFModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("LDXPS.Domain.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CDCL");

                    b.Property<Guid?>("CodigoVendedor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CDVEND");

                    b.Property<decimal>("LimiteCredito")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("DSLIM");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DSNOME");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasDefaultValue("PF")
                        .HasColumnName("IDTIPO");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoVendedor");

                    b.ToTable("CLIENTES");
                });

            modelBuilder.Entity("LDXPS.Domain.Entidades.Vendedor", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CDVEND");

                    b.Property<int>("CodigoPrecoPadrao")
                        .HasColumnType("int")
                        .HasColumnName("CDTAB");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTNASC");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DSNOME");

                    b.HasKey("Codigo");

                    b.ToTable("VENDEDORES");
                });

            modelBuilder.Entity("LDXPS.Domain.Entidades.Cliente", b =>
                {
                    b.HasOne("LDXPS.Domain.Entidades.Vendedor", "Vendedor")
                        .WithMany("Clientes")
                        .HasForeignKey("CodigoVendedor");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("LDXPS.Domain.Entidades.Vendedor", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
